#!/bin/bash

start () {
    if [[ $1 != "-od" ]]; then
        docker compose up -d
        docker compose logs -f
    fi
}

kill () {
    docker compose kill
}

down() {
    docker compose down --volumes
}

containerName=$(docker ps | grep -iP '4456' | grep -ioP '[A-Za-z]+-minetrax-\d')

while (( $# )); do
    case $1 in
        -e|--exec)
            docker exec -ti --workdir /home/mt $containerName /bin/bash
            shift 2
        ;;

        -c|--command)
            docker exec --workdir /home/mt $containerName php artisan $2
            shift 2
        ;;

        -rp|--reset-password)
            docker exec --workdir /home/mt $containerName php artisan auth:password:reset superadmin
            shift 1
        ;;

        -s|--start)
            start

            shift 1
        ;;

        -r|--restart)
            kill
            down

            start

            shift 1
        ;;

        -k|--kill)
            kill

            shift 1
        ;;

        -d|--destroy)
            kill
            down

            shift 1
        ;;
    esac
done