#!/bin/bash

start () {
    docker compose up -d
    docker compose logs -f
}

kill () {
    docker compose kill
}

down() {
    [[ $deleteVolumes ]] && vol=--volumes

    docker compose down $vol
}

while (( $# )); do
    case $1 in
        -e|--exec)
            docker exec -ti --workdir /home/mt minetrax /bin/bash
            shift 2
        ;;

        -c|--command)
            docker exec --workdir /home/mt minetrax php artisan $2
            shift 2
        ;;

        -rp|--reset-password)
            docker exec --workdir /home/mt minetrax php artisan auth:password:reset superadmin
            shift 1
        ;;

        -s|--start)
            start

            shift 1
        ;;

        -r|--restart)
            kill
            down

            start

            shift 1
        ;;

        -k|--kill)
            kill

            shift 1
        ;;

        -d|--destroy)
            kill
            down

            shift 1
        ;;

        -da|--destroy-all)
            deleteVolumes=true

            kill
            down

            shift 1
        ;;
    esac
done