#!/bin/sh
### BEGIN INIT INFO
# Provides:          MineTrax Worker
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start/stop my custom service
# Description:       Start/stop my custom service
### END INIT INFO

NAME="minetrax-worker"
DAEMON="/usr/bin/php /home/mt/artisan queue:work"
PIDFILE="/var/run/$NAME.pid"

start() {
    echo "Starting $NAME..."
    start-stop-daemon --start --background --make-pidfile --pidfile $PIDFILE --exec $DAEMON
}

stop() {
    echo "Stopping $NAME..."
    start-stop-daemon --stop --pidfile $PIDFILE --retry 10
    rm -f $PIDFILE
}

case "$1" in
    start)
        start
    ;;

    stop)
        stop
    ;;

    restart)
        stop
        start
    ;;

    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
    ;;
esac

exit 0